"""Striver 180 — Team Dashboard (Streamlit).

Reads the JSON already generated by GitHub Actions (generated/dashboard.json,
generated/history.jsonl, data/problems.json) and renders the team's progress.

Run locally:  streamlit run app.py
Deploy:       link this repo on Streamlit Community Cloud, main branch, app.py
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import streamlit as st

ROOT = Path(__file__).resolve().parent
DASH_PATH = ROOT / "generated" / "dashboard.json"
HISTORY_PATH = ROOT / "generated" / "history.jsonl"
PROBLEMS_PATH = ROOT / "data" / "problems.json"


@st.cache_data(ttl=300)
def load_data() -> dict:
    dash = json.loads(DASH_PATH.read_text())
    probs = json.loads(PROBLEMS_PATH.read_text())
    history = [
        json.loads(ln)
        for ln in HISTORY_PATH.read_text().splitlines()
        if ln.strip()
    ]
    return {"dash": dash, "probs": probs, "history": history}


def problems_df(problems: list[dict]) -> pd.DataFrame:
    return pd.DataFrame(problems)


def member_problem_rows(member: dict, probs: list[dict]) -> pd.DataFrame:
    by_id = {p["id"]: p for p in probs}
    rows = []
    for pid in member.get("solved_ids", []):
        p = by_id.get(pid)
        if p is None:
            continue
        rows.append(
            {
                "id": pid,
                "day": p.get("day"),
                "name": p.get("name"),
                "topic": p.get("topic"),
                "difficulty": p.get("difficulty"),
                "slug": p.get("slug"),
            }
        )
    return pd.DataFrame(rows, columns=["id", "day", "name", "topic", "difficulty", "slug"])


def main() -> None:
    st.set_page_config(page_title="Striver 180 — Dashboard", layout="wide")

    data = load_data()
    dash, probs, history = data["dash"], data["probs"], data["history"]

    st.title("🚀 Striver 180 — Team Dashboard")

    generated_at = dash.get("generated_at", "—")
    st.caption(f"Sheet totals powered by each member's repo · last generated {generated_at} UTC")

    # ---- header metrics ----
    cols = st.columns(4)
    cols[0].metric("Team solved", f"{dash['total']} / {dash['sheet_total']}")
    cols[1].metric("Members", len(dash["members"]))
    cols[2].metric("Sheet total", dash["sheet_total"])

    with cols[3]:
        pct = 100.0 * dash["total"] / dash["sheet_total"] if dash["sheet_total"] else 0.0
        st.metric("Progress", f"{pct:.1f}%")

    # ---- leaderboard ----
    st.subheader("🏆 Leaderboard")
    lb = []
    for m in dash["members"]:
        lb.append(
            {
                "Member": m["display"],
                "Solved": m["solved"],
                "Remaining": dash["sheet_total"] - m["solved"],
                "Topic coverage": ", ".join(f"{k}: {v}" for k, v in (m.get("topics") or {}).items()),
            }
        )
    df_lb = pd.DataFrame(lb).sort_values("Solved", ascending=False).reset_index(drop=True)
    st.dataframe(df_lb, use_container_width=True, hide_index=True)

    # per-member progress bars
    for m in dash["members"]:
        frac = m["solved"] / dash["sheet_total"] if dash["sheet_total"] else 0.0
        st.progress(min(frac, 1.0), text=f"{m['display']}: {m['solved']} / {dash['sheet_total']} solved")

    st.divider()

    # ---- per-member drill-down ----
    st.subheader("🧑‍💻 Per-member progress")
    member_map = {m["id"]: m for m in dash["members"]}
    sel = st.selectbox("Select member", list(member_map.keys()), format_func=lambda i: member_map[i]["display"])
    member = member_map[sel]

    rows = member_problem_rows(member, probs)
    if rows.empty:
        st.info("No solved problems recorded yet.")
    else:
        c1, c2 = st.columns(2)
        with c1:
            st.markdown("**Topic breakdown**")
            st.dataframe(
                rows["topic"].value_counts().rename_axis("Topic").reset_index(name="Solved"),
                use_container_width=True,
                hide_index=True,
            )
            st.markdown("**Difficulty breakdown**")
            st.dataframe(
                rows["difficulty"].value_counts().rename_axis("Difficulty").reset_index(name="Solved"),
                use_container_width=True,
                hide_index=True,
            )
        with c2:
            st.markdown("**Solved problems**")
            st.dataframe(rows, use_container_width=True, hide_index=True)

    st.divider()

    # ---- topic heatmap ----
    st.subheader("🗂️ Topic coverage")
    topic_order = dash.get("topic_order", [])
    heat = {}
    for m in dash["members"]:
        for topic, cnt in (m.get("topics") or {}).items():
            heat.setdefault(topic, {})[m["display"]] = cnt
    topics = [t for t in topic_order if t in heat] or list(heat)
    index_ = [t for t in topics]
    data_ = [[heat[t].get(m["display"], 0) for m in dash["members"]] for t in index_]
    df_heat = pd.DataFrame(data_, index=index_, columns=[m["display"] for m in dash["members"]])
    st.dataframe(df_heat, use_container_width=True)

    st.divider()

    # ---- recent activity ----
    st.subheader("🕒 Recent activity")
    recent = dash.get("recent_activity", [])
    if recent:
        st.dataframe(
            pd.DataFrame(recent)[["when", "member", "problem", "topic", "difficulty"]],
            use_container_width=True,
            hide_index=True,
        )

    # ---- history timeline ----
    if history:
        st.subheader("📈 Solved over time")
        hist_df = pd.DataFrame(history)
        hist_df["generated_at"] = pd.to_datetime(hist_df["generated_at"])
        hist_df = hist_df.sort_values("generated_at")
        line = pd.DataFrame(hist_df["members"].apply(pd.Series)).set_index(hist_df["generated_at"])
        st.line_chart(line)


if __name__ == "__main__":
    main()