#!/usr/bin/env python3
"""
Generate data/problems.json — the canonical Striver SDE Sheet problem list.

The sheet is the authentic takeUforward "Striver's SDE Sheet" (advertised as 180
problems; the published list currently contains 191 distinct rows across 27
days). Every row below is transcribed from that sheet — problem names and
difficulties are taken directly from the published sheet, they are not invented.

Each problem gets:
  id         unique canonical id (1..N, sheet order)
  day        day number from the sheet (1..27)
  section    exact sheet section heading
  topic      consolidated topic group
  name       canonical display name (sheet name, lightly cleaned)
  difficulty Easy/Medium/Hard (None where the sheet does not say)
  judge      leetcode | gfg | codingninjas | other | none
  slug       preferred canonical slug used for matching
  aliases    extra slugs accepted when matching member submissions
  link       primary judge URL when one exists

Usage:
    python3 problems_builder.py  (writes ../data/problems.json)
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "data" / "problems.json"

# day -> (section, topic)
SECTIONS = {
    1: ("Arrays", "Arrays"),
    2: ("Arrays Part-II", "Arrays"),
    3: ("Arrays Part-III", "Arrays"),
    4: ("Arrays Part-IV", "Arrays"),
    5: ("Linked List", "Linked List"),
    6: ("Linked List Part-II", "Linked List"),
    7: ("Linked List and Arrays", "Linked List"),
    8: ("Greedy Algorithm", "Greedy"),
    9: ("Recursion", "Recursion"),
    10: ("Recursion and Backtracking", "Recursion"),
    11: ("Binary Search", "Binary Search"),
    12: ("Heaps", "Heaps"),
    13: ("Stack and Queue", "Stack & Queue"),
    14: ("Stack and Queue Part-II", "Stack & Queue"),
    15: ("String", "Strings"),
    16: ("String Part-II", "Strings"),
    17: ("Binary Tree", "Binary Tree"),
    18: ("Binary Tree Part-II", "Binary Tree"),
    19: ("Binary Tree Part-III", "Binary Tree"),
    20: ("Binary Search Tree", "BST"),
    21: ("Binary Search Tree Part-II", "BST"),
    22: ("Binary Trees [Miscellaneous]", "Binary Tree"),
    23: ("Graph", "Graph"),
    24: ("Graph Part-II", "Graph"),
    25: ("Dynamic Programming", "Dynamic Programming"),
    26: ("Dynamic Programming Part-II", "Dynamic Programming"),
    27: ("Trie", "Trie"),
}

# (day, num) -> (name, difficulty)  -- transcribed verbatim from the sheet.
SHEET = {
    (1, 1): ("Set Matrix Zeroes", "Medium"),
    (1, 2): ("Pascal's Triangle", "Medium"),
    (1, 3): ("Next Permutation", "Medium"),
    (1, 4): ("Kadane's Algorithm", "Easy"),
    (1, 5): ("Sort an Array of 0s, 1s and 2s", "Medium"),
    (1, 6): ("Best Time to Buy and Sell Stock", "Easy"),
    (2, 1): ("Rotate Image", "Medium"),
    (2, 2): ("Merge Overlapping Subintervals", "Medium"),
    (2, 3): ("Merge Two Sorted Arrays without Extra Space", "Medium"),
    (2, 4): ("Find the Duplicate in an Array of N+1 Integers", "Medium"),
    (2, 5): ("Repeat and Missing Number", "Hard"),
    (2, 6): ("Inversion of Array", "Medium"),
    (3, 1): ("Search a 2D Matrix", "Medium"),
    (3, 2): ("Pow(x, n)", "Medium"),
    (3, 3): ("Majority Element (> n/2)", "Easy"),
    (3, 4): ("Majority Element (> n/3)", "Medium"),
    (3, 5): ("Grid Unique Paths", "Medium"),
    (3, 6): ("Reverse Pairs", "Medium"),
    (4, 1): ("2Sum Problem", "Medium"),
    (4, 2): ("4-Sum Problem", "Hard"),
    (4, 3): ("Longest Consecutive Sequence", "Medium"),
    (4, 4): ("Largest Subarray with 0 Sum", "Medium"),
    (4, 5): ("Count Number of Subarrays with given XOR K", "Hard"),
    (4, 6): ("Longest Substring without Repeating Characters", "Medium"),
    (5, 1): ("Reverse a Linked List", "Easy"),
    (5, 2): ("Find the Middle of Linked List", "Easy"),
    (5, 3): ("Merge Two Sorted Linked Lists", "Medium"),
    (5, 4): ("Remove N-th Node from Back of Linked List", "Medium"),
    (5, 5): ("Add Two Numbers as Linked List", "Medium"),
    (5, 6): ("Delete a Given Node in a Linked List (O(1))", "Medium"),
    (6, 1): ("Find Intersection Point of Y Linked List", "Medium"),
    (6, 2): ("Detect a Cycle in a Linked List", "Medium"),
    (6, 3): ("Reverse a Linked List in Groups of Size k", "Hard"),
    (6, 4): ("Check if a Linked List is Palindrome or not", "Medium"),
    (6, 5): ("Find the Starting Point of the Loop of Linked List", "Medium"),
    (6, 6): ("Flattening of a Linked List", "Medium"),
    (7, 1): ("Rotate a Linked List", "Medium"),
    (7, 2): ("Clone a Linked List with Random and Next Pointer", "Hard"),
    (7, 3): ("3Sum", "Medium"),
    (7, 4): ("Trapping Rainwater", "Hard"),
    (7, 5): ("Remove Duplicates from Sorted Array", "Easy"),
    (7, 6): ("Max Consecutive Ones", "Easy"),
    (8, 1): ("N Meetings in One Room", "Medium"),
    (8, 2): ("Minimum Number of Platforms Required for a Railway", "Medium"),
    (8, 3): ("Job Sequencing Problem", "Medium"),
    (8, 4): ("Fractional Knapsack Problem", "Medium"),
    (8, 5): ("Greedy Algorithm to Find Minimum Number of Coins", "Medium"),
    (8, 6): ("Assign Cookies", "Medium"),
    (9, 1): ("Subset Sums", "Medium"),
    (9, 2): ("Subset-II", "Medium"),
    (9, 3): ("Combination Sum 1", "Medium"),
    (9, 4): ("Combination Sum 2", "Medium"),
    (9, 5): ("Palindrome Partitioning", "Medium"),
    (9, 6): ("K-th Permutation Sequence", "Medium"),
    (10, 1): ("Print All Permutations of a String/Array", "Medium"),
    (10, 2): ("N Queens Problem", "Hard"),
    (10, 3): ("Sudoku Solver", "Hard"),
    (10, 4): ("M Coloring Problem", "Hard"),
    (10, 5): ("Rat in a Maze", "Hard"),
    (10, 6): ("Word Break (print all ways)", "Medium"),
    (11, 1): ("Nth Root of an Integer", "Easy"),
    (11, 2): ("Matrix Median", "Hard"),
    (11, 3): ("Single Element in a Sorted Array", "Medium"),
    (11, 4): ("Search in a Sorted and Rotated Array", "Medium"),
    (11, 5): ("Median of 2 Sorted Arrays", "Hard"),
    (11, 6): ("K-th Element of Two Sorted Arrays", "Medium"),
    (11, 7): ("Allocate Minimum Number of Pages", "Hard"),
    (11, 8): ("Aggressive Cows", "Medium"),
    (12, 1): ("Max/Min Heap Implementation", "Medium"),
    (12, 2): ("Kth Largest Element in an Array", "Easy"),
    (12, 3): ("Maximum Sum Combination", "Medium"),
    (12, 4): ("Find Median from Data Stream", "Hard"),
    (12, 5): ("Merge K Sorted Arrays", "Medium"),
    (12, 6): ("K Most Frequent Elements", "Medium"),
    (13, 1): ("Implement Stack using Arrays", "Easy"),
    (13, 2): ("Implement Queue using Arrays", "Easy"),
    (13, 3): ("Implement Stack using Queue", "Medium"),
    (13, 4): ("Implement Queue using Stack", "Medium"),
    (13, 5): ("Check for Balanced Parentheses", "Medium"),
    (13, 6): ("Next Greater Element", "Easy"),
    (13, 7): ("Sort a Stack", "Medium"),
    (14, 1): ("Next Smaller Element", "Easy"),
    (14, 2): ("LRU Cache", "Hard"),
    (14, 3): ("LFU Cache", "Hard"),
    (14, 4): ("Largest Rectangle in a Histogram", "Medium"),
    (14, 5): ("Sliding Window Maximum", "Hard"),
    (14, 6): ("Implement Min Stack", "Medium"),
    (14, 7): ("Rotten Orange (Using BFS)", "Medium"),
    (14, 8): ("Stock Span Problem", "Medium"),
    (14, 9): ("Maximum of Minimums of Every Window Size", "Medium"),
    (14, 10): ("The Celebrity Problem", "Medium"),
    (15, 1): ("Reverse Words in a String", "Easy"),
    (15, 2): ("Longest Palindromic Substring", "Medium"),
    (15, 3): ("Roman Number to Integer and vice versa", "Easy"),
    (15, 4): ("Implement ATOI / STRSTR", "Medium"),
    (15, 5): ("Longest Common Prefix", "Easy"),
    (15, 6): ("Rabin Karp", None),
    (16, 1): ("Z-Function", "Easy"),
    (16, 2): ("KMP Algorithm / LPS Array", "Hard"),
    (16, 3): ("Shortest Palindrome (add chars at front)", "Hard"),
    (16, 4): ("Valid Anagram (Check for Anagrams)", "Easy"),
    (16, 5): ("Count and Say", "Medium"),
    (16, 6): ("Compare Version Numbers", "Easy"),
    (17, 1): ("Binary Tree Inorder Traversal", "Easy"),
    (17, 2): ("Binary Tree Preorder Traversal", "Easy"),
    (17, 3): ("Binary Tree Postorder Traversal", "Easy"),
    (17, 4): ("Morris Inorder Traversal", "Medium"),
    (17, 5): ("Morris Preorder Traversal", "Medium"),
    (17, 6): ("Left View of Binary Tree", "Easy"),
    (17, 7): ("Bottom View of Binary Tree", "Medium"),
    (17, 8): ("Top View of Binary Tree", "Easy"),
    (17, 9): ("Single-Stack Traversal (Three Orders at Once)", "Medium"),
    (17, 10): ("Vertical Order Traversal", "Easy"),
    (17, 11): ("Root to Node Path in Binary Tree", "Medium"),
    (17, 12): ("Maximum Width of Binary Tree", "Medium"),
    (18, 1): ("Binary Tree Level Order Traversal", "Easy"),
    (18, 2): ("Height of a Binary Tree", "Medium"),
    (18, 3): ("Diameter of Binary Tree", "Medium"),
    (18, 4): ("Check if the Binary Tree is Height-Balanced", "Medium"),
    (18, 5): ("LCA in Binary Tree", "Medium"),
    (18, 6): ("Check if Two Trees Are Identical", "Medium"),
    (18, 7): ("Zig Zag Traversal of Binary Tree", "Easy"),
    (18, 8): ("Boundary Traversal of Binary Tree", "Medium"),
    (19, 1): ("Maximum Path Sum", "Hard"),
    (19, 2): ("Construct Binary Tree from Inorder and Preorder", "Hard"),
    (19, 3): ("Construct Binary Tree from Inorder and Postorder", "Hard"),
    (19, 4): ("Symmetric Binary Tree", "Medium"),
    (19, 5): ("Flatten Binary Tree to Linked List", "Hard"),
    (19, 6): ("Mirror of a Binary Tree", "Medium"),
    (19, 7): ("Check for Children Sum Property", "Medium"),
    (20, 1): ("Populate Next Right Pointers of Tree", "Medium"),
    (20, 2): ("Search a Given Key in BST", "Easy"),
    (20, 3): ("Convert Sorted Array to Binary Search Tree", "Hard"),
    (20, 4): ("Construct a BST from a Preorder Traversal", "Medium"),
    (20, 5): ("Validate Binary Search Tree", "Medium"),
    (20, 6): ("Find LCA of Two Nodes in BST", "Medium"),
    (20, 7): ("Inorder Predecessor / Successor in BST", "Medium"),
    (21, 1): ("Floor in a BST", "Easy"),
    (21, 2): ("Ceil in a BST", "Easy"),
    (21, 3): ("K-th Smallest Element in BST", "Medium"),
    (21, 4): ("K-th Largest Element in BST", "Medium"),
    (21, 5): ("Two Sum IV - Input is a BST", "Medium"),
    (21, 6): ("BST Iterator", "Medium"),
    (21, 7): ("Size of the Largest BST in a Binary Tree", "Medium"),
    (21, 8): ("Serialize and Deserialize Binary Tree", "Medium"),
    (22, 1): ("Binary Tree to Doubly Linked List", "Medium"),
    (22, 2): ("Find Median in a Stream of Running Integers", "Hard"),
    (22, 3): ("K-th Largest Element in a Stream", "Easy"),
    (22, 4): ("Distinct Numbers in Every Window", "Medium"),
    (22, 5): ("K-th Largest Element in an Unsorted Array", "Easy"),
    (22, 6): ("Flood-Fill Algorithm", "Medium"),
    (23, 1): ("Clone a Graph", "Hard"),
    (23, 2): ("DFS Traversal of a Graph", "Hard"),
    (23, 3): ("BFS Traversal of a Graph", "Medium"),
    (23, 4): ("Detect Cycle in Undirected Graph (BFS)", "Hard"),
    (23, 5): ("Detect Cycle in Undirected Graph (DFS)", "Hard"),
    (23, 6): ("Detect Cycle in Directed Graph (DFS)", "Hard"),
    (23, 7): ("Detect Cycle in Directed Graph (BFS)", "Hard"),
    (23, 8): ("Topological Sort (BFS)", "Hard"),
    (23, 9): ("Topological Sort (DFS)", "Hard"),
    (23, 10): ("Number of Islands", "Hard"),
    (23, 11): ("Bipartite Check using BFS", "Medium"),
    (23, 12): ("Bipartite Check using DFS", "Hard"),
    (24, 1): ("Strongly Connected Components (Kosaraju)", "Hard"),
    (24, 2): ("Dijkstra's Algorithm", "Hard"),
    (24, 3): ("Bellman-Ford Algorithm", "Hard"),
    (24, 4): ("Floyd Warshall Algorithm", "Hard"),
    (24, 5): ("MST using Prim's Algorithm", "Hard"),
    (24, 6): ("MST using Kruskal's Algorithm", "Hard"),
    (25, 1): ("Maximum Product Subarray", "Medium"),
    (25, 2): ("Longest Increasing Subsequence", "Medium"),
    (25, 3): ("Longest Common Subsequence", "Medium"),
    (25, 4): ("0-1 Knapsack", "Medium"),
    (25, 5): ("Edit Distance", "Hard"),
    (25, 6): ("Maximum Sum Increasing Subsequence", "Hard"),
    (25, 7): ("Matrix Chain Multiplication", "Hard"),
    (26, 1): ("Minimum Path Sum in a Matrix", "Medium"),
    (26, 2): ("Coin Change", "Hard"),
    (26, 3): ("Subset Sum Problem", "Medium"),
    (26, 4): ("Rod Cutting", "Hard"),
    (26, 5): ("Egg Dropping Puzzle", "Hard"),
    (26, 6): ("Word Break", "Medium"),
    (26, 7): ("Palindrome Partitioning II (MCM variation)", "Hard"),
    (26, 8): ("Maximum Profit in Job Scheduling", "Hard"),
    (27, 1): ("Implement Trie (Prefix Tree)", "Hard"),
    (27, 2): ("Implement Trie II", "Hard"),
    (27, 3): ("Longest String with All Prefixes", "Medium"),
    (27, 4): ("Number of Distinct Substrings in a String", "Hard"),
    (27, 5): ("Power Set", "Medium"),
    (27, 6): ("Maximum XOR of Two Numbers in an Array", "Medium"),
    (27, 7): ("Maximum XOR With an Element From Array", "Hard"),
}

# (day, num) -> canonical info for matching: (judge, slug, link, aliases)
LINKS = {
    (1, 1): ("leetcode", "set-matrix-zeroes", "https://leetcode.com/problems/set-matrix-zeroes/", ["set-matrix-zeros", "setmatrixzeroes"]),
    (1, 2): ("leetcode", "pascals-triangle", "https://leetcode.com/problems/pascals-triangle/", ["pascal-triangle", "pascal-s-triangle", "pascalstriangle"]),
    (1, 3): ("leetcode", "next-permutation", "https://leetcode.com/problems/next-permutation/", ["nextpermutation"]),
    (1, 4): ("leetcode", "maximum-subarray", "https://leetcode.com/problems/maximum-subarray/", ["kadane-s-algorithm", "kadanes-algorithm", "max-subarray-sum", "maximumsubarray"]),
    (1, 5): ("leetcode", "sort-colors", "https://leetcode.com/problems/sort-colors/", ["sort-an-array-of-0s-1s-and-2s", "sort-an-array-of-0s-1-s-and-2-s", "sort-an-array-of-0s-1s-2s", "dutch-national-flag-algorithm", "sort-0-1-2", "sortcolors"]),
    (1, 6): ("leetcode", "best-time-to-buy-and-sell-stock", "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", ["stock-buy-and-sell", "buy-and-sell-stock", "besttimetobuyandsellstock"]),
    (2, 1): ("leetcode", "rotate-image", "https://leetcode.com/problems/rotate-image/", ["rotate-matrix", "rotateimage"]),
    (2, 2): ("leetcode", "merge-intervals", "https://leetcode.com/problems/merge-intervals/", ["merge-overlapping-subintervals", "merge-overlapping-intervals", "mergeintervals"]),
    (2, 3): ("leetcode", "merge-sorted-array", "https://leetcode.com/problems/merge-sorted-array/", ["merge-two-sorted-arrays-without-extra-space", "merge-2-sorted-arrays-without-extra-space", "merge-two-sorted-arrays", "mergesortedarray"]),
    (2, 4): ("leetcode", "find-the-duplicate-number", "https://leetcode.com/problems/find-the-duplicate-number/", ["find-the-duplicate-in-an-array-of-n1-integers", "duplicate-in-array", "find-the-duplicate-in-an-array-of-n-1-integers"]),
    (2, 5): ("gfg", "find-missing-and-repeating", "https://practice.geeksforgeeks.org/problems/find-missing-and-repeating2512/1", ["repeat-and-missing-number", "find-repeating-and-missing", "missing-and-repeating"]),
    (2, 6): ("codingninjas", "count-inversions", "https://www.codingninjas.com/studio/problems/count-inversions_615", ["inversion-of-array", "count-inversions-in-an-array", "inversion-count"]),
    (3, 1): ("leetcode", "search-a-2d-matrix", "https://leetcode.com/problems/search-a-2d-matrix/", ["search-in-a-2-d-matrix", "search-a-2d-matrix-ii", "searcha2dmatrix"]),
    (3, 2): ("leetcode", "powx-n", "https://leetcode.com/problems/powx-n/", ["pow-x-n", "pow-x-n", "pow", "powxn"]),
    (3, 3): ("leetcode", "majority-element", "https://leetcode.com/problems/majority-element/", ["majority-element-n-2", "majority-element-greater-than-n-2", "majority-element-n2", "majorityelement"]),
    (3, 4): ("leetcode", "majority-element-ii", "https://leetcode.com/problems/majority-element-ii/", ["majority-element-n-3", "majority-element-n3", "majorityelementii"]),
    (3, 5): ("leetcode", "unique-paths", "https://leetcode.com/problems/unique-paths/", ["grid-unique-paths", "unique-path", "uniquepaths"]),
    (3, 6): ("leetcode", "reverse-pairs", "https://leetcode.com/problems/reverse-pairs/", ["reversepairs"]),
    (4, 1): ("leetcode", "two-sum", "https://leetcode.com/problems/two-sum/", ["2-sum", "2sum", "twosum"]),
    (4, 2): ("leetcode", "4sum", "https://leetcode.com/problems/4sum/", ["4-sum", "4-sum-problem", "4sum-problem", "four-sum", "foursum"]),
    (4, 3): ("leetcode", "longest-consecutive-sequence", "https://leetcode.com/problems/longest-consecutive-sequence/", ["longest-consecutive-subsequence", "longestconsecutivesequence"]),
    (4, 4): ("gfg", "largest-subarray-with-0-sum", "https://practice.geeksforgeeks.org/problems/largest-subarray-with-0-sum/1", ["largest-subarray-with-k-sum", "largest-subarray-with-zero-sum", "largest-subarray-with-0-sum", "longest-subarray-with-zero-sum"]),
    (4, 5): ("codingninjas", "count-subarrays-with-given-xor", "https://www.codingninjas.com/studio/problems/count-subarrays-with-given-xor", ["count-number-of-subarrays-with-given-xor-k", "subarray-with-given-xor", "count-subarrays-with-given-xor-k"]),
    (4, 6): ("leetcode", "longest-substring-without-repeating-characters", "https://leetcode.com/problems/longest-substring-without-repeating-characters/", ["longest-substring-without-repeat", "longest-substring-without-repeating", "longestsubstringwithoutrepeatingcharacters"]),
    (5, 1): ("leetcode", "reverse-linked-list", "https://leetcode.com/problems/reverse-linked-list/", ["reverse-a-linked-list", "reverselinkedlist", "reverse-a-linkedlist"]),
    (5, 2): ("leetcode", "middle-of-the-linked-list", "https://leetcode.com/problems/middle-of-the-linked-list/", ["find-the-middle-of-linkedlist", "find-the-middle-of-linked-list", "middle-of-a-linked-list", "middleofthelinkedlist"]),
    (5, 3): ("leetcode", "merge-two-sorted-lists", "https://leetcode.com/problems/merge-two-sorted-lists/", ["merge-two-sorted-linked-list", "merge-2-sorted-linked-list", "merge-two-sorted-linkedlists", "mergetwosortedlists"]),
    (5, 4): ("leetcode", "remove-nth-node-from-end-of-list", "https://leetcode.com/problems/remove-nth-node-from-end-of-list/", ["remove-n-th-node-from-back-of-linkedlist", "remove-nth-node-from-back-of-linked-list", "remove-nth-node-from-end", "removenthnodefromendoflist"]),
    (5, 5): ("leetcode", "add-two-numbers", "https://leetcode.com/problems/add-two-numbers/", ["add-two-numbers-as-linkedlist", "add-two-numbers-as-linked-list", "addtwonumbers"]),
    (5, 6): ("leetcode", "delete-node-in-a-linked-list", "https://leetcode.com/problems/delete-node-in-a-linked-list/", ["delete-a-given-node-when-a-node-is-given", "delete-a-node-in-a-linked-list", "delete-node-when-node-is-given", "deletenodeinalinkedlist"]),
    (6, 1): ("leetcode", "intersection-of-two-linked-lists", "https://leetcode.com/problems/intersection-of-two-linked-lists/", ["find-intersection-point-of-y-linkedlist", "find-intersection-point-of-y-linked-list", "intersection-point-of-two-linked-lists", "intersectionoftwolinkedlists"]),
    (6, 2): ("leetcode", "linked-list-cycle", "https://leetcode.com/problems/linked-list-cycle/", ["detect-a-cycle-in-linked-list", "detect-cycle-in-a-linked-list", "linkedlistcycle"]),
    (6, 3): ("leetcode", "reverse-nodes-in-k-group", "https://leetcode.com/problems/reverse-nodes-in-k-group/", ["reverse-a-linked-list-in-groups-of-size-k", "reverse-a-linkedlist-in-groups-of-size-k", "reversenodesinkgroup"]),
    (6, 4): ("leetcode", "palindrome-linked-list", "https://leetcode.com/problems/palindrome-linked-list/", ["check-if-a-linked-list-is-palindrome", "check-if-a-linkedlist-is-palindrome-or-not", "palindromelinkedlist"]),
    (6, 5): ("leetcode", "linked-list-cycle-ii", "https://leetcode.com/problems/linked-list-cycle-ii/", ["find-the-starting-point-of-the-loop-of-linkedlist", "find-the-starting-point-of-the-loop-of-linked-list", "starting-point-of-loop", "linkedlistcycleii"]),
    (6, 6): ("gfg", "flattening-a-linked-list", "https://practice.geeksforgeeks.org/problems/flattening-a-linked-list/1", ["flattening-of-a-linked-list", "flatten-a-linked-list", "flatteningalist"]),
    (7, 1): ("leetcode", "rotate-list", "https://leetcode.com/problems/rotate-list/", ["rotate-a-linked-list", "rotate-a-linkedlist", "rotatelist"]),
    (7, 2): ("leetcode", "copy-list-with-random-pointer", "https://leetcode.com/problems/copy-list-with-random-pointer/", ["clone-a-linked-list-with-random-and-next-pointer", "clone-list-with-random-pointer", "copy-list-with-random-pointers", "copylistwithrandompointer"]),
    (7, 3): ("leetcode", "3sum", "https://leetcode.com/problems/3sum/", ["3-sum", "three-sum", "threesum", "3sum-problem"]),
    (7, 4): ("leetcode", "trapping-rain-water", "https://leetcode.com/problems/trapping-rain-water/", ["trapping-rainwater", "trappingrainwater", "trapping-rain-water"]),
    (7, 5): ("leetcode", "remove-duplicates-from-sorted-array", "https://leetcode.com/problems/remove-duplicates-from-sorted-array/", ["remove-duplicate-from-sorted-array", "removeduplicatesfromsortedarray"]),
    (7, 6): ("leetcode", "max-consecutive-ones", "https://leetcode.com/problems/max-consecutive-ones/", ["max-consecutive-1s", "maximum-consecutive-ones", "maxconsecutiveones"]),
    (8, 1): ("gfg", "n-meetings-in-one-room", "https://practice.geeksforgeeks.org/problems/n-meetings-in-one-room-1587115620/1", ["meeting-room-problem", "meetings-in-one-room", "n-meetings-in-a-room"]),
    (8, 2): ("gfg", "minimum-platforms", "https://practice.geeksforgeeks.org/problems/minimum-platforms-1587115620/1", ["minimum-number-of-platforms-required-for-a-railway", "min-number-of-platforms-required", "min-platforms", "minimumnumberofplatforms"]),
    (8, 3): ("gfg", "job-sequencing-problem", "https://practice.geeksforgeeks.org/problems/job-sequencing-problem-1587115620/1", ["job-sequencing", "job-sequencing-with-deadlines"]),
    (8, 4): ("gfg", "fractional-knapsack", "https://practice.geeksforgeeks.org/problems/fractional-knapsack-1587115620/1", ["fractional-knapsack-problem"]),
    (8, 5): ("gfg", "find-minimum-number-of-coins", "https://practice.geeksforgeeks.org/problems/-minimum-number-of-coins4426/1", ["greedy-algorithm-to-find-minimum-number-of-coins", "minimum-number-of-coins", "min-number-of-coins"]),
    (8, 6): ("leetcode", "assign-cookies", "https://leetcode.com/problems/assign-cookies/", ["assigncookies"]),
    (9, 1): ("gfg", "subset-sums", "https://practice.geeksforgeeks.org/problems/subset-sums2234/1", ["subset-sum-i", "subset-sum-no-duplicates", "subsetsums"]),
    (9, 2): ("leetcode", "subsets-ii", "https://leetcode.com/problems/subsets-ii/", ["subset-sum-ii", "subsetsii"]),
    (9, 3): ("leetcode", "combination-sum", "https://leetcode.com/problems/combination-sum/", ["combination-sum-1", "combination-sum-i", "combinationsum"]),
    (9, 4): ("leetcode", "combination-sum-ii", "https://leetcode.com/problems/combination-sum-ii/", ["combination-sum-2", "combinationsumii"]),
    (9, 5): ("leetcode", "palindrome-partitioning", "https://leetcode.com/problems/palindrome-partitioning/", ["palindromepartitioning"]),
    (9, 6): ("leetcode", "permutation-sequence", "https://leetcode.com/problems/permutation-sequence/", ["k-th-permutation-sequence", "kth-permutation-sequence", "kthpermutationsequence", "permutationsequence"]),
    (10, 1): ("leetcode", "permutations", "https://leetcode.com/problems/permutations/", ["print-all-permutations-of-a-string", "print-all-permutations-of-an-array", "permutations-of-an-array", "print-all-permutations"]),
    (10, 2): ("leetcode", "n-queens", "https://leetcode.com/problems/n-queens/", ["n-queens-problem", "nqueens"]),
    (10, 3): ("leetcode", "sudoku-solver", "https://leetcode.com/problems/sudoku-solver/", ["sudukosolver", "solve-sudoku", "sudokusolver"]),
    (10, 4): ("gfg", "m-coloring-problem", "https://practice.geeksforgeeks.org/problems/m-coloring-problem-1587115620/1", ["graph-coloring-problem", "m-coloring", "mcolor"]),
    (10, 5): ("gfg", "rat-in-a-maze-problem", "https://practice.geeksforgeeks.org/problems/rat-in-a-maze-problem/1", ["rat-in-a-maze", "ratinamaze"]),
    (10, 6): ("leetcode", "word-break-ii", "https://leetcode.com/problems/word-break-ii/", ["word-break-print-all-ways", "word-break-2", "word-break-ii-print-ways", "wordbreakii"]),
    (11, 1): ("codingninjas", "nth-root-of-integer", "https://www.codingninjas.com/studio/problems/1062679", ["the-n-th-root-of-an-integer", "nth-root-of-a-number", "n-th-root-of-an-integer", "nth-root"]),
    (11, 2): ("codingninjas", "matrix-median", "https://www.codingninjas.com/studio/problems/median-of-a-row-wise-sorted-matrix", ["median-of-a-row-wise-sorted-matrix", "matrix-median"]),
    (11, 3): ("leetcode", "single-element-in-a-sorted-array", "https://leetcode.com/problems/single-element-in-a-sorted-array/", ["find-the-element-that-appears-once-in-a-sorted-array", "single-element-in-sorted-array", "singleelementinasortedarray"]),
    (11, 4): ("leetcode", "search-in-rotated-sorted-array", "https://leetcode.com/problems/search-in-rotated-sorted-array/", ["search-element-in-a-sorted-and-rotated-array", "search-in-rotated-sorted-array-find-pivot", "searchrotatedsortedarray", "search-in-a-rotated-sorted-array"]),
    (11, 5): ("leetcode", "median-of-two-sorted-arrays", "https://leetcode.com/problems/median-of-two-sorted-arrays/", ["median-of-2-sorted-arrays", "medianoftwosortedarrays"]),
    (11, 6): ("gfg", "k-th-element-of-two-sorted-array", "https://practice.geeksforgeeks.org/problems/k-th-element-of-two-sorted-array1317/1", ["kth-element-of-2-sorted-arrays", "kth-element-of-two-sorted-arrays", "kth-element-of-two-sorted-array"]),
    (11, 7): ("gfg", "allocate-minimum-number-of-pages", "https://practice.geeksforgeeks.org/problems/allocate-minimum-number-of-pages0937/1", ["allocate-minimum-number-of-pages", "allocate-min-num-of-pages", "book-allocation-problem", "allocate-books"]),
    (11, 8): ("gfg", "aggressive-cows", "https://practice.geeksforgeeks.org/problems/aggressive-cows/1", ["aggressivecows"]),
    (12, 1): ("none", "heap-implementation", None, ["max-heap-min-heap-implementation", "implement-heap", "max-heap-and-min-heap", "implement-min-heap", "implement-max-heap"]),
    (12, 2): ("leetcode", "kth-largest-element-in-an-array", "https://leetcode.com/problems/kth-largest-element-in-an-array/", ["kth-largest-element-in-a-array", "kth-largest-element", "kthlargestelementinanarray"]),
    (12, 3): ("codingninjas", "maximum-sum-combination", "https://www.codingninjas.com/studio/problems/maximum-sum-combination_1133002", ["maximum-sum-combination"]),
    (12, 4): ("leetcode", "find-median-from-data-stream", "https://leetcode.com/problems/find-median-from-data-stream/", ["find-median-from-a-data-stream", "median-in-a-stream", "findmedianfromdatastream"]),
    (12, 5): ("leetcode", "merge-k-sorted-lists", "https://leetcode.com/problems/merge-k-sorted-lists/", ["merge-k-sorted-arrays", "merge-ksorted-lists", "mergeksortedlists"]),
    (12, 6): ("leetcode", "top-k-frequent-elements", "https://leetcode.com/problems/top-k-frequent-elements/", ["k-most-frequent-elements", "top-k-frequent", "topkfrequentelements"]),
    (13, 1): ("none", "implement-stack-using-array", None, ["implement-stack-using-arrays", "implement-a-stack-using-array", "stack-using-array", "stack-implementation-using-array"]),
    (13, 2): ("none", "implement-queue-using-array", None, ["implement-queue-using-arrays", "implement-a-queue-using-array", "queue-using-array", "queue-implementation-using-array"]),
    (13, 3): ("leetcode", "implement-stack-using-queues", "https://leetcode.com/problems/implement-stack-using-queues/", ["implement-stack-using-queue", "implement-stack-using-a-single-queue", "implementstackusingqueues"]),
    (13, 4): ("leetcode", "implement-queue-using-stacks", "https://leetcode.com/problems/implement-queue-using-stacks/", ["implement-queue-using-stack", "implementqueueusingstacks"]),
    (13, 5): ("leetcode", "valid-parentheses", "https://leetcode.com/problems/valid-parentheses/", ["check-for-balanced-parentheses", "balanced-parentheses", "balanced-paranthesis", "valid-parentheses", "validparentheses"]),
    (13, 6): ("leetcode", "next-greater-element-i", "https://leetcode.com/problems/next-greater-element-i/", ["next-greater-element", "nextgreaterelement", "next-greater-element-i"]),
    (13, 7): ("gfg", "sort-a-stack", "https://practice.geeksforgeeks.org/problems/sort-a-stack/1", ["sort-stack-recur", "sorta-stack", "stack-sort"]),
    (14, 1): ("gfg", "next-smaller-element", "https://practice.geeksforgeeks.org/problems/next-smaller-element2214/1", ["next-smaller-element", "next-greater-to-left", "nextsmallerelement"]),
    (14, 2): ("leetcode", "lru-cache", "https://leetcode.com/problems/lru-cache/", ["lru-cache-implementation", "lrucache"]),
    (14, 3): ("leetcode", "lfu-cache", "https://leetcode.com/problems/lfu-cache/", ["lfucache"]),
    (14, 4): ("leetcode", "largest-rectangle-in-histogram", "https://leetcode.com/problems/largest-rectangle-in-histogram/", ["largest-rectangle-in-histogram", "largestrectangleinhistogram"]),
    (14, 5): ("leetcode", "sliding-window-maximum", "https://leetcode.com/problems/sliding-window-maximum/", ["sliding-window-maximum", "slidingwindowmaximum", "sliding-window-max"]),
    (14, 6): ("leetcode", "min-stack", "https://leetcode.com/problems/min-stack/", ["implement-min-stack", "minstack-problem", "minstack"]),
    (14, 7): ("leetcode", "rotten-oranges", "https://leetcode.com/problems/rotten-oranges/", ["rotten-orange", "rotting-oranges", "rottenoranges"]),
    (14, 8): ("leetcode", "online-stock-span", "https://leetcode.com/problems/online-stock-span/", ["stock-span-problem", "stock-span", "onlinestockspan"]),
    (14, 9): ("gfg", "maximum-of-minimum-for-every-window-size", "https://practice.geeksforgeeks.org/problems/maximum-of-minimum-for-every-window-size3453/1", ["find-the-maximum-of-minimums-of-every-window-size", "maximum-of-minimums-of-every-window-size", "max-of-min-for-every-window"]),
    (14, 10): ("gfg", "the-celebrity-problem", "https://practice.geeksforgeeks.org/problems/the-celebrity-problem/1", ["celebrity-problem", "celebrity"]),
    (15, 1): ("leetcode", "reverse-words-in-a-string", "https://leetcode.com/problems/reverse-words-in-a-string/", ["reverse-words-in-a-string", "reverse-words-of-a-string", "reversewordsinastring"]),
    (15, 2): ("leetcode", "longest-palindromic-substring", "https://leetcode.com/problems/longest-palindromic-substring/", ["longest-palindrome-in-a-string", "longest-palindromic-substring", "longestpalindromicsubstring"]),
    (15, 3): ("leetcode", "roman-to-integer", "https://leetcode.com/problems/roman-to-integer/", ["roman-number-to-integer-and-vice-versa", "roman-to-integer-and-integer-to-roman", "integer-to-roman", "roman-to-int", "romantointeger"]),
    (15, 4): ("leetcode", "string-to-integer-atoi", "https://leetcode.com/problems/string-to-integer-atoi/", ["implement-atoi-strstr", "atoi-strstr", "implement-atoi", "string-to-integer", "stringtointegeratoi", "implement-strstr"]),
    (15, 5): ("leetcode", "longest-common-prefix", "https://leetcode.com/problems/longest-common-prefix/", ["longestcommonprefix"]),
    (15, 6): ("other", "rabin-karp", None, ["rabin-karp-pattern-searching", "rabin-karp-algorithm", "rabinkarp"]),
    (16, 1): ("other", "z-function", None, ["z-function", "z-algorithm", "zalgorithm", "zfunction"]),
    (16, 2): ("other", "kmp-algorithm", None, ["kmp-algo-lps-pi-array", "kmp-algorithm-lps", "kmp-string-matching", "kmp-algo", "lps-array", "kmp"]),
    (16, 3): ("leetcode", "shortest-palindrome", "https://leetcode.com/problems/shortest-palindrome/", ["minimum-character-to-be-added-at-front-to-make-string-palindrome", "minimum-characters-to-be-added-at-front-to-make-string-palindrome", "minimum-characters-needed-to-be-inserted-in-the-beginning-to-make-it-palindromic", "add-characters-at-front-to-make-palindrome", "shortestpalindrome"]),
    (16, 4): ("leetcode", "valid-anagram", "https://leetcode.com/problems/valid-anagram/", ["check-for-anagrams", "anagram-check", "valid-anagram", "validanagram"]),
    (16, 5): ("leetcode", "count-and-say", "https://leetcode.com/problems/count-and-say/", ["countandsay"]),
    (16, 6): ("leetcode", "compare-version-numbers", "https://leetcode.com/problems/compare-version-numbers/", ["compareversionnumbers"]),
    (17, 1): ("leetcode", "binary-tree-inorder-traversal", "https://leetcode.com/problems/binary-tree-inorder-traversal/", ["inorder-traversal", "inorder-traversal-of-binary-tree", "binarytreeinordertraversal"]),
    (17, 2): ("leetcode", "binary-tree-preorder-traversal", "https://leetcode.com/problems/binary-tree-preorder-traversal/", ["preorder-traversal", "preorder-traversal-of-binary-tree", "binarytreepreordertraversal"]),
    (17, 3): ("leetcode", "binary-tree-postorder-traversal", "https://leetcode.com/problems/binary-tree-postorder-traversal/", ["postorder-traversal", "postorder-traversal-of-binary-tree", "binarytreepostordertraversal"]),
    (17, 4): ("other", "morris-inorder-traversal", None, ["morris-inorder", "morris-inorder-of-binary-tree", "morrisinorder"]),
    (17, 5): ("other", "morris-preorder-traversal", None, ["morris-preorder", "morris-preorder-of-binary-tree", "morrispreorder"]),
    (17, 6): ("other", "left-view-of-binary-tree", None, ["left-view-of-a-binary-tree", "left-view-of-binary-tree", "leftview", "left-view-of-a-tree"]),
    (17, 7): ("other", "bottom-view-of-binary-tree", None, ["bottom-view-of-a-binary-tree", "bottom-view", "bottomview"]),
    (17, 8): ("other", "top-view-of-binary-tree", None, ["top-view-of-a-binary-tree", "top-view", "topview"]),
    (17, 9): ("other", "single-traversal-all-orders", None, ["preorder-inorder-postorder-in-single-traversal", "preorder-inorder-postorder-in-a-single-traversal", "all-traversals-in-one", "three-traversals-in-one"]),
    (17, 10): ("leetcode", "vertical-order-traversal-of-a-binary-tree", "https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/", ["vertical-order-traversal", "vertical-order-of-a-binary-tree", "verticalordertraversal"]),
    (17, 11): ("other", "root-to-node-path", None, ["root-to-node-path-in-binary-tree", "root-to-node-path-in-a-binary-tree", "print-root-to-node-path", "path-to-a-node"]),
    (17, 12): ("leetcode", "maximum-width-of-binary-tree", "https://leetcode.com/problems/maximum-width-of-binary-tree/", ["max-width-of-a-binary-tree", "max-width-of-binary-tree", "maximumwidthofbinarytree"]),
    (18, 1): ("leetcode", "binary-tree-level-order-traversal", "https://leetcode.com/problems/binary-tree-level-order-traversal/", ["level-order-traversal", "level-order-traversal-in-spiral-form", "levelordertraversal", "level-order-of-a-binary-tree"]),
    (18, 2): ("leetcode", "maximum-depth-of-binary-tree", "https://leetcode.com/problems/maximum-depth-of-binary-tree/", ["height-of-a-binary-tree", "height-of-binary-tree", "maximumdepthofbinarytree"]),
    (18, 3): ("leetcode", "diameter-of-binary-tree", "https://leetcode.com/problems/diameter-of-binary-tree/", ["diameter-of-a-binary-tree", "diameterofbinarytree"]),
    (18, 4): ("leetcode", "balanced-binary-tree", "https://leetcode.com/problems/balanced-binary-tree/", ["check-if-the-binary-tree-is-height-balanced", "check-if-binary-tree-is-height-balanced", "height-balanced-binary-tree", "balancedbinarytree"]),
    (18, 5): ("leetcode", "lowest-common-ancestor-of-a-binary-tree", "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/", ["lca-in-binary-tree", "lca-of-a-binary-tree", "lowest-common-ancestor", "lowestcommonancestorofabinarytree"]),
    (18, 6): ("leetcode", "same-tree", "https://leetcode.com/problems/same-tree/", ["check-if-two-trees-are-identical-or-not", "check-if-two-trees-are-identical", "identical-trees", "sametree"]),
    (18, 7): ("leetcode", "binary-tree-zigzag-level-order-traversal", "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/", ["zig-zag-traversal-of-binary-tree", "zigzag-traversal", "zig-zag-level-order-traversal", "zigzag-level-order-traversal", "binarytreezigzaglevelordertraversal"]),
    (18, 8): ("other", "boundary-traversal-of-binary-tree", None, ["boundary-traversal-of-a-binary-tree", "boundary-traversal", "boundarytraversal"]),
    (19, 1): ("leetcode", "binary-tree-maximum-path-sum", "https://leetcode.com/problems/binary-tree-maximum-path-sum/", ["maximum-path-sum", "max-path-sum-of-a-binary-tree", "binarytreemaximumpathsum"]),
    (19, 2): ("leetcode", "construct-binary-tree-from-preorder-and-inorder-traversal", "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/", ["construct-binary-tree-from-inorder-and-preorder", "build-tree-from-inorder-and-preorder", "constructtree-in-pre"]),
    (19, 3): ("leetcode", "construct-binary-tree-from-inorder-and-postorder-traversal", "https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/", ["construct-binary-tree-from-inorder-and-postorder", "build-tree-from-inorder-and-postorder", "constructtree-in-post"]),
    (19, 4): ("leetcode", "symmetric-tree", "https://leetcode.com/problems/symmetric-tree/", ["symmetric-binary-tree", "symmetrictree"]),
    (19, 5): ("leetcode", "flatten-binary-tree-to-linked-list", "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/", ["flatten-binary-tree-to-linkedlist", "flattenbinarytreetolinkedlist"]),
    (19, 6): ("other", "mirror-binary-tree", None, ["check-if-binary-tree-is-the-mirror-of-itself", "mirror-of-a-binary-tree", "mirror-of-a-tree", "check-for-mirror"]),
    (19, 7): ("other", "children-sum-property", None, ["check-for-children-sum-property", "children-sum-property-in-a-binary-tree", "children-sum-property"]),
    (20, 1): ("leetcode", "populating-next-right-pointers-in-each-node", "https://leetcode.com/problems/populating-next-right-pointers-in-each-node/", ["populate-next-right-pointers-of-tree", "populate-next-right-pointers", "next-right-pointers-in-each-node", "populating-next-right-pointers"]),
    (20, 2): ("leetcode", "search-in-a-binary-search-tree", "https://leetcode.com/problems/search-in-a-binary-search-tree/", ["search-given-key-in-bst", "search-a-node-in-bst", "searchinabinarysearchtree"]),
    (20, 3): ("leetcode", "convert-sorted-array-to-binary-search-tree", "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/", ["construct-bst-from-given-keys", "construct-bst-from-sorted-array", "sorted-array-to-bst", "convertsortedarraytobinarysearchtree"]),
    (20, 4): ("leetcode", "construct-binary-search-tree-from-preorder-traversal", "https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal/", ["construct-a-bst-from-a-preorder-traversal", "bst-from-preorder", "constructbstfrompreorder"]),
    (20, 5): ("leetcode", "validate-binary-search-tree", "https://leetcode.com/problems/validate-binary-search-tree/", ["check-if-a-bt-is-bst-or-not", "check-if-a-binary-tree-is-bst", "is-binary-search-tree", "valid-bst", "validatebinarysearchtree"]),
    (20, 6): ("leetcode", "lowest-common-ancestor-of-a-binary-search-tree", "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/", ["find-lca-of-two-nodes-in-bst", "lca-in-bst", "lca-of-bst", "lowestcommonancestorofabinarysearchtree"]),
    (20, 7): ("other", "inorder-predecessor-and-successor", None, ["find-the-inorder-predecessor-successor-of-a-given-key-in-bst", "inorder-predecessor-and-successor-in-bst", "predecessor-and-successor-in-bst", "pred-succ-bst"]),
    (21, 1): ("other", "floor-in-bst", None, ["floor-of-a-given-key-in-bst", "floor-of-a-node-in-bst", "floor-of-bst", "floor-bst"]),
    (21, 2): ("other", "ceil-in-bst", None, ["ceil-of-a-given-key-in-bst", "ceil-of-a-node-in-bst", "ceil-of-bst", "ceil-bst"]),
    (21, 3): ("leetcode", "kth-smallest-element-in-a-bst", "https://leetcode.com/problems/kth-smallest-element-in-a-bst/", ["find-kth-smallest-element-in-bst", "k-th-smallest-element-in-bst", "kthsmallestelementinabst"]),
    (21, 4): ("other", "kth-largest-element-in-bst", None, ["find-kth-largest-element-in-bst", "k-th-largest-element-in-bst", "kth-largest-bst"]),
    (21, 5): ("leetcode", "two-sum-iv-input-is-a-bst", "https://leetcode.com/problems/two-sum-iv-input-is-a-bst/", ["find-a-pair-with-a-given-sum-in-bst", "pair-with-given-sum-in-bst", "two-sum-in-bst", "twosumiv"]),
    (21, 6): ("leetcode", "binary-search-tree-iterator", "https://leetcode.com/problems/binary-search-tree-iterator/", ["bst-iterator", "binarysearchtreeiterator"]),
    (21, 7): ("other", "size-of-largest-bst", None, ["size-of-the-largest-bst-in-a-binary-tree", "largest-bst-in-a-binary-tree", "largest-bst", "size-of-largest-bst-in-bt"]),
    (21, 8): ("leetcode", "serialize-and-deserialize-binary-tree", "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/", ["serialize-deserialize-binary-tree", "serialize-and-deserialize-bt", "serializeanddeserializebinarytree"]),
    (22, 1): ("other", "binary-tree-to-dll", None, ["binary-tree-to-double-linked-list", "binary-tree-to-doubly-linked-list", "convert-binary-tree-to-dll", "bttodll"]),
    (22, 2): ("leetcode", "find-median-from-data-stream", "https://leetcode.com/problems/find-median-from-data-stream/", ["find-median-in-a-stream-of-running-integers", "running-median", "median-in-a-stream-of-running-integers"]),
    (22, 3): ("leetcode", "kth-largest-element-in-a-stream", "https://leetcode.com/problems/kth-largest-element-in-a-stream/", ["k-th-largest-element-in-a-stream", "kthlargestelementinastream"]),
    (22, 4): ("other", "distinct-numbers-in-window", None, ["count-distinct-elements-in-every-window", "distinct-numbers-in-window", "distinct-elements-in-window", "count-distinct-elements-in-every-window-of-size-k"]),
    (22, 5): ("leetcode", "kth-largest-element-in-an-array", "https://leetcode.com/problems/kth-largest-element-in-an-array/", ["kth-largest-element-in-an-unsorted-array", "kth-largest-in-unsorted-array"]),
    (22, 6): ("leetcode", "flood-fill", "https://leetcode.com/problems/flood-fill/", ["flood-fill-algorithm", "floodfill"]),
    (23, 1): ("leetcode", "clone-graph", "https://leetcode.com/problems/clone-graph/", ["clone-a-graph", "clonegraph"]),
    (23, 2): ("other", "dfs-of-graph", None, ["dfs", "dfs-traversal-of-a-graph", "dfs-traversal", "dfs-of-a-graph"]),
    (23, 3): ("other", "bfs-of-graph", None, ["bfs", "bfs-traversal-of-a-graph", "bfs-traversal", "bfs-of-a-graph"]),
    (23, 4): ("other", "cycle-detection-undirected-bfs", None, ["detect-a-cycle-in-undirected-graph-using-bfs", "detect-cycle-in-undirected-graph-bfs", "cycle-in-undirected-graph-bfs"]),
    (23, 5): ("other", "cycle-detection-undirected-dfs", None, ["detect-a-cycle-in-undirected-graph-using-dfs", "detect-cycle-in-undirected-graph-dfs", "cycle-in-undirected-graph-dfs"]),
    (23, 6): ("other", "cycle-detection-directed-dfs", None, ["detect-a-cycle-in-a-directed-graph-using-dfs", "detect-cycle-in-directed-graph-dfs", "cycle-in-directed-graph-dfs"]),
    (23, 7): ("other", "cycle-detection-directed-bfs", None, ["detect-a-cycle-in-a-directed-graph-using-bfs", "detect-cycle-in-directed-graph-bfs", "cycle-in-directed-graph-bfs", "detect-cycle-in-a-directed-graph-using-topo-sort"]),
    (23, 8): ("other", "topological-sort-bfs", None, ["topological-sort-using-bfs", "topo-sort-bfs", "topological-sort-kahns"]),
    (23, 9): ("other", "topological-sort-dfs", None, ["topological-sort-using-dfs", "topo-sort-dfs", "topological-sort"]),
    (23, 10): ("leetcode", "number-of-islands", "https://leetcode.com/problems/number-of-islands/", ["number-of-islands-in-grid-and-graph", "count-number-of-islands", "numberofislands"]),
    (23, 11): ("other", "bipartite-check-bfs", None, ["bipartite-check-using-bfs", "is-graph-bipartite-bfs", "bipartite-graph-bfs"]),
    (23, 12): ("other", "bipartite-check-dfs", None, ["bipartite-check-using-dfs", "is-graph-bipartite-dfs", "bipartite-graph-dfs"]),
    (24, 1): ("other", "kosarajus-algorithm", None, ["strongly-connected-component-using-kosaraju", "strongly-connected-components", "kosaraju-s-algo", "scc-kosaraju", "kosaraju"]),
    (24, 2): ("other", "dijkstra-algorithm", None, ["dijkstra-s-algorithm", "dijkstra", "dijkstras-algorithm"]),
    (24, 3): ("other", "bellman-ford-algorithm", None, ["bellman-ford-algo", "bellman-ford", "bellmanford"]),
    (24, 4): ("other", "floyd-warshall-algorithm", None, ["floyd-warshall-algo", "floyd-warshall", "floydwarshall"]),
    (24, 5): ("other", "prims-algorithm", None, ["mst-using-prim-s-algo", "prims-mst", "minimum-spanning-tree-prims", "prim-s-algorithm"]),
    (24, 6): ("other", "kruskals-algorithm", None, ["mst-using-kruskal-s-algo", "kruskals-mst", "minimum-spanning-tree-kruskal"]),
    (25, 1): ("leetcode", "maximum-product-subarray", "https://leetcode.com/problems/maximum-product-subarray/", ["max-product-subarray", "maximumproductsubarray"]),
    (25, 2): ("leetcode", "longest-increasing-subsequence", "https://leetcode.com/problems/longest-increasing-subsequence/", ["longest-increasing-subsequence", "lis", "longestincreasingsubsequence"]),
    (25, 3): ("leetcode", "longest-common-subsequence", "https://leetcode.com/problems/longest-common-subsequence/", ["longest-common-subsequence", "lcs", "longestcommonsubsequence"]),
    (25, 4): ("other", "0-1-knapsack", None, ["0-1-knapsack-problem", "knapsack-problem", "knapsack-0-1", "zero-one-knapsack"]),
    (25, 5): ("leetcode", "edit-distance", "https://leetcode.com/problems/edit-distance/", ["edit-distance", "editdistance"]),
    (25, 6): ("other", "maximum-sum-increasing-subsequence", None, ["maximum-sum-increasing-subsequence", "max-sum-increasing-subsequence", "msis"]),
    (25, 7): ("other", "matrix-chain-multiplication", None, ["matrix-chain-multiplication", "mcm", "matrix-chain-multiplication-problem"]),
    (26, 1): ("leetcode", "minimum-path-sum", "https://leetcode.com/problems/minimum-path-sum/", ["minimum-sum-path-in-the-matrix", "min-path-sum-in-matrix", "minimum-path-sum-in-a-matrix", "minimumpathsum"]),
    (26, 2): ("leetcode", "coin-change", "https://leetcode.com/problems/coin-change/", ["coin-change-1", "minimum-coins-to-make-sum", "coinchange"]),
    (26, 3): ("other", "subset-sum-problem", None, ["subset-sum", "subset-sum-dp", "subset-sum-with-dp", "subset-sum-problem-dp"]),
    (26, 4): ("other", "rod-cutting", None, ["rod-cutting-problem", "rod-cutting-dp", "rodcutting"]),
    (26, 5): ("other", "egg-dropping-puzzle", None, ["egg-dropping", "egg-drop-problem", "egg-dropping-puzzle-dp", "super-egg-drop"]),
    (26, 6): ("leetcode", "word-break", "https://leetcode.com/problems/word-break/", ["word-break-dp", "wordbreak"]),
    (26, 7): ("leetcode", "palindrome-partitioning-ii", "https://leetcode.com/problems/palindrome-partitioning-ii/", ["palindrome-partitioning-mcm-variation", "palindrome-partitioning-2", "min-cuts-palindrome-partitioning", "palindromepartitioningii"]),
    (26, 8): ("leetcode", "maximum-profit-in-job-scheduling", "https://leetcode.com/problems/maximum-profit-in-job-scheduling/", ["maximum-profit-job-scheduling", "job-scheduling-with-profit", "maximumprofitinjobscheduling"]),
    (27, 1): ("leetcode", "implement-trie-prefix-tree", "https://leetcode.com/problems/implement-trie-prefix-tree/", ["implement-trie", "trie-implementation", "implementtrie"]),
    (27, 2): ("other", "implement-trie-2", None, ["implement-trie-ii", "implement-trie-2-prefix-tree", "trie-ii", "implement-trie-ii-prefix-tree"]),
    (27, 3): ("other", "longest-string-with-all-prefixes", None, ["longest-word-with-all-prefixes", "longest-string-with-all-prefixes", "longest-string-that-is-a-prefix-of-all-strings"]),
    (27, 4): ("other", "number-of-distinct-substrings", None, ["number-of-distinct-substrings-in-a-string", "count-distinct-substrings", "distinct-substrings-using-trie", "count-number-of-distinct-substrings"]),
    (27, 5): ("leetcode", "subsets", "https://leetcode.com/problems/subsets/", ["power-set", "power-set-problem", "subsets-power-set", "powerset", "subsets-of-an-array"]),
    (27, 6): ("leetcode", "maximum-xor-of-two-numbers-in-an-array", "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/", ["max-xor-of-two-numbers", "maximumxor-array", "maximumxor"]),
    (27, 7): ("leetcode", "maximum-xor-with-an-element-from-array", "https://leetcode.com/problems/maximum-xor-with-an-element-from-array/", ["maximum-xor-with-element-from-array", "max-xor-with-element-from-array", "maximumxor)fromarray"]),
}

# shared concern: (12,4) and (22,2) both map to find-median-from-data-stream
#               (12,2) and (22,5) both map to kth-largest-element-in-an-array
# The reverse index in the generator resolves identical slugs to the FIRST entry
# in sheet order; the later duplicates keep their own id and can still be matched
# through their distinct alternative aliases.

def normalize(s: str) -> str:
    s = s.lower().replace("’", "'").replace("‘", "'")
    s = s.replace("“", '"').replace("”", '"')
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s


def slugify(name: str) -> str:
    return normalize(name)


def main() -> None:
    problems = []
    for day in sorted(SECTIONS):
        section, topic = SECTIONS[day]
        for num in sorted(k[1] for k in SHEET if k[0] == day):
            name, diff = SHEET[(day, num)]
            judge, slug, link, aliases = LINKS[(day, num)]
            rec = {
                "id": len(problems) + 1,
                "day": day,
                "section": section,
                "topic": topic,
                "name": name,
                "difficulty": diff,
                "judge": judge,
                "slug": slug,
                "link": link,
                "aliases": [slugify(a) for a in aliases],
            }
            problems.append(rec)

    slugs = {}
    for p in problems:
        slugs.setdefault(p["slug"], []).append(p["id"])
    dup = {k: v for k, v in slugs.items() if len(v) > 1}
    if dup:
        print("WARNING shared slugs:", dup)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(problems, indent=2, ensure_ascii=False) + "\n")
    print(f"Wrote {len(problems)} problems -> {OUT}")
    print("Difficulty counts:", json.dumps(
        {k: sum(1 for p in problems if p['difficulty'] == k)
         for k in sorted({p['difficulty'] for p in problems} | {None}, key=lambda x: str(x))},
        default=str))


if __name__ == "__main__":
    main()